production:
  adapter: postgresql
  database: ticket_prod
  host: localhost
  username: ticket
  password: ticket
  encoding: utf8

test:
  adapter: postgresql
  database: ticket_test
  host: localhost
  username: ticket
  password: ticket
  encoding: utf8

development:
  adapter: postgresql
  database: ticket_dev
  host: localhost
  username: ticket
  password: ticket
  encoding: utf8
